---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: true
  tasks:
  - name: Comprobar si existe archivo comprimido
    ansible.builtin.stat:
      path: /tmp/result_auditoria.tgz
    delegate_to: localhost
    register: fichero

  
  - name: Verificación
    ansible.builtin.assert:
      that: fichero.stat.exists
      success_msg: "El fichero /tmp/result_auditoria.tgz existe"
      fail_msg: "El fichero /tmp/result_auditoria.tgz no existe"
    delegate_to: localhost

...